# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-08 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=200)),
                ('bill', models.IntegerField(default=0)),
                ('length', models.FloatField()),
                ('quality', models.CharField(choices=[('raymond', 'Raymond'), ('grasim', 'Grasim'), ('reidandtaylor', 'Reid and Taylor'), ('vimal', 'Vimal'), ('reliance', 'Reliance'), ('custom', 'custom')], default='custom', max_length=20)),
                ('rate', models.FloatField()),
            ],
        ),
    ]
