# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('value', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='sale',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sale',
            name='tax',
            field=models.IntegerField(default=0),
        ),
    ]
