# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-08 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='quality',
            field=models.CharField(choices=[['raymond', 'Raymond'], ['grasim', 'Grasim'], ['reidandtaylor', 'Reid and Taylor'], ['vimal', 'Vimal'], ['reliance', 'Reliance'], ['custom', 'custom']], default='custom', max_length=20),
        ),
    ]
