# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_auto_20170126_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='phone',
            field=models.BigIntegerField(default=0),
        ),
    ]
