# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-08 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_auto_20170108_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='length',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='description',
            name='quality',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='description',
            name='rate',
            field=models.IntegerField(default=0),
        ),
    ]
