# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-08 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0005_auto_20170108_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='bill',
            field=models.FloatField(max_length=200),
        ),
        migrations.AlterField(
            model_name='description',
            name='length',
            field=models.FloatField(max_length=200),
        ),
        migrations.AlterField(
            model_name='description',
            name='rate',
            field=models.FloatField(max_length=200),
        ),
    ]
