# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-12 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0006_auto_20170108_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party', models.CharField(max_length=200)),
                ('inovice', models.FloatField(max_length=200)),
                ('amount', models.FloatField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/products/main')),
                ('image_caption', models.CharField(default='null', max_length=200)),
            ],
        ),
    ]
