# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-12 16:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0007_bill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='description',
            old_name='bill',
            new_name='billing',
        ),
    ]
