# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-12 16:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0008_auto_20170112_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='party',
        ),
    ]
