# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0008_bill_bill_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='bill_image',
        ),
        migrations.AddField(
            model_name='bill',
            name='bill_name',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AlterField(
            model_name='bill',
            name='party',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
