# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-12 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0009_remove_bill_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='party',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
