# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-12 16:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0010_bill_party'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='image',
        ),
    ]
