# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-12 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0011_remove_bill_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/products/main'),
        ),
    ]
