# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-12 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0012_bill_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
