# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-12 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0013_auto_20170112_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='image',
            field=models.ImageField(blank=True, default='media/2016.jpg', upload_to='media'),
        ),
    ]
